version: "3"

services:
  nginx:
    build: requirements/nginx
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - emallah_network
    volumes:
      - wordpress:/var/www/html

  mariadb:
    build: requirements/mariadb
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3306"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - emallah_network

  wordpress:
    build: requirements/wordpress
    image: wordpress
    restart: always
    container_name: wordpress
    ports:
      - "9000"
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - emallah_network

networks:
  emallah_network:

volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/emallah/data/files
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/emallah/data/db
      o: bind
